In [1]:
import numpy as np

In [2]:
heights=[189,170,189,163,183,171,185,168,173,183,
         173,173,175,178,183,193,178,173,174,183,
         183,180,168,180,170,178,182,180,183,178,
         182,188,175,179,183,193,182,183,177,185,
        188,188,182,185,191]
ages=[57,61,57,57,58,57,61,54,68,51,
      49,64,50,48,65,52,56,46,54,49,
      51,47,55,55,54,42,51,56,55,51,
      54,51,60,62,43,55,56,61,52,69,   
      64,46,54,47,70]
height_arr=np.array(heights)
age_arr=np.array(ages)

In [3]:
print(height_arr.size)
print(height_arr.shape)
print((height_arr>188).sum())
print(age_arr.size)
print(age_arr.shape)
print((age_arr>52).sum())

45
(45,)
5
45
(45,)
28


In [4]:
height_188=height_arr>188
print(height_188)
print(height_188.sum())

[ True False  True False False False False False False False False False
 False False False  True False False False False False False False False
 False False False False False False False False False False False  True
 False False False False False False False False  True]
5


In [5]:
height_age=heights+ages
height_age_arr=np.array(height_age)
print(height_age_arr)
print(height_age_arr.shape)
height_age_arr=height_age_arr.reshape(2,45)
print(height_age_arr)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
 182 183 177 185 188 188 182 185 191  57  61  57  57  58  57  61  54  68
  51  49  64  50  48  65  52  56  46  54  49  51  47  55  55  54  42  51
  56  55  51  54  51  60  62  43  55  56  61  52  69  64  46  54  47  70]
(90,)
[[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
  174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
  182 183 177 185 188 188 182 185 191]
 [ 57  61  57  57  58  57  61  54  68  51  49  64  50  48  65  52  56  46
   54  49  51  47  55  55  54  42  51  56  55  51  54  51  60  62  43  55
   56  61  52  69  64  46  54  47  70]]


In [6]:
hg=height_arr.reshape(-1,45)
hg
print(hg.shape)
height_arr[0]=195.5
height_arr

(1, 45)


array([195, 170, 189, 163, 183, 171, 185, 168, 173, 183, 173, 173, 175,
       178, 183, 193, 178, 173, 174, 183, 183, 180, 168, 180, 170, 178,
       182, 180, 183, 178, 182, 188, 175, 179, 183, 193, 182, 183, 177,
       185, 188, 188, 182, 185, 191])

In [7]:
age_arr.shape
age_arr[:3,]

array([57, 61, 57])

hstack

In [12]:
age_arr.reshape(45,1)
height_arr.reshape(45,1)
height_age_arr=np.hstack((height_arr,age_arr)) #Chu y hai ngoac don
print(height_age_arr)
print(height_age_arr.shape)
print(height_age_arr[:3,])

[195 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
 182 183 177 185 188 188 182 185 191  57  61  57  57  58  57  61  54  68
  51  49  64  50  48  65  52  56  46  54  49  51  47  55  55  54  42  51
  56  55  51  54  51  60  62  43  55  56  61  52  69  64  46  54  47  70]
(90,)
[195 170 189]


vstack

In [18]:
age_arr.reshape(1,45)
height_arr.reshape(1,45)
height_age_arr=np.vstack((height_arr,age_arr)) #Chu y hai ngoac don
print(height_age_arr)
print(height_age_arr.shape)
print(height_age_arr[:,:4])

[[195 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
  174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
  182 183 177 185 188 188 182 185 191]
 [ 57  61  57  57  58  57  61  54  68  51  49  64  50  48  65  52  56  46
   54  49  51  47  55  55  54  42  51  56  55  51  54  51  60  62  43  55
   56  61  52  69  64  46  54  47  70]]
(2, 45)
[[195 170 189 163]
 [ 57  61  57  57]]


In [31]:
print(height_age_arr[:3,])
print(height_age_arr[:3,0])
print(height_age_arr[:3,:3])
print(height_age_arr[:,0])
print(height_age_arr.shape)

[[195 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
  174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
  182 183 177 185 188 188 182 185 191]
 [ 57  61  57  57  58  57  61  54  68  51  49  64  50  48  65  52  56  46
   54  49  51  47  55  55  54  42  51  56  55  51  54  51  60  62  43  55
   56  61  52  69  64  46  54  47  70]]
[195  57]
[[195 170 189]
 [ 57  61  57]]
[195  57]
(2, 45)


In [40]:
height_age_arr0=np.concatenate((height_arr,age_arr))
print(height_age_arr)
print(height_age_arr.shape) #(2,45)
height_age_arr0=np.concatenate((height_arr,age_arr),axis=0)
print(height_age_arr0)
print(height_age_arr0.shape) #(90,)
height_arr1=height_arr.reshape(1,45)
age_arr1=age_arr.reshape(1,45)
height_age_arr1=np.concatenate((height_arr1,age_arr1),axis=1)
print(height_age_arr1)
print(height_age_arr1.shape) #(1,90)

[[195 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
  174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
  182 183 177 185 188 188 182 185 191]
 [ 57  61  57  57  58  57  61  54  68  51  49  64  50  48  65  52  56  46
   54  49  51  47  55  55  54  42  51  56  55  51  54  51  60  62  43  55
   56  61  52  69  64  46  54  47  70]]
(2, 45)
[195 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
 182 183 177 185 188 188 182 185 191  57  61  57  57  58  57  61  54  68
  51  49  64  50  48  65  52  56  46  54  49  51  47  55  55  54  42  51
  56  55  51  54  51  60  62  43  55  56  61  52  69  64  46  54  47  70]
(90,)
[[195 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
  174 183 183 180 168 180 170 178 182 180 183 178 182 188 175 179 183 193
  182 183 177 185 188 188 182 185 191  57  61  57  57  58  57  61  54  68
   51  49  64  50  48  

In [46]:
arr1=np.array([[1,2],[2,3],[3,4],[5,6],[2,2]]) #shape (5,2)
arr2=np.array([[6],[7],[8],[9],[10]]) # shape (5,1)
#arr3=np.concatenate((arr1,arr2),axis=0) # Error
#print(arr3)
#print(arr3.shape)
arr4=np.concatenate((arr1,arr2),axis=1) #
print(arr4)
print(arr4.shape)
arr5=np.hstack((arr1,arr2))
print(arr5)
print(arr5.shape)

[[ 1  2  6]
 [ 2  3  7]
 [ 3  4  8]
 [ 5  6  9]
 [ 2  2 10]]
(5, 3)
[[ 1  2  6]
 [ 2  3  7]
 [ 3  4  8]
 [ 5  6  9]
 [ 2  2 10]]
(5, 3)
