In [1]:
import numpy as np
np.set_printoptions(precision=2)

In [2]:
X=np.matrix([[1,0],[0,2.00]])
print(X.T)

[[1. 0.]
 [0. 2.]]


In [3]:
det=np.linalg.det(X)
print(det)

2.0


In [4]:
X_1=np.linalg.inv(X)
print(X_1)

[[1.  0. ]
 [0.  0.5]]


In [5]:
Y=np.matrix([2,3])
print(Y)

[[2 3]]


In [6]:
print(Y)

[[2 3]]


In [7]:
C=np.array(Y*X_1)[0]
print(C)

[2.  1.5]


In [8]:
B=np.array2string(C,separator=',',floatmode='unique')
print(B)

[2. ,1.5]


In [9]:
A=np.matrix([[1,2],[1, 0.5],[1,0.3]])
B=np.matrix([3,3.5,3.2])
C=np.array([[3.42], [-0.2]]).reshape(1,2)
print(C)

[[ 3.42 -0.2 ]]
